package j3;

import a3.InterfaceC0106a;
import b3.AbstractC0219i;
import g3.InterfaceC0466p;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import p3.AbstractC0779w;
import p3.InterfaceC0761e;
import p3.InterfaceC0765i;
import r0.AbstractC0807a;
import u3.C0881c;
import u3.C0884f;

/* renamed from: j3.t, reason: case insensitive filesystem */
/* loaded from: classes.dex */
public final class C0579t extends b3.k implements InterfaceC0106a {

    /* renamed from: d, reason: collision with root package name */
    public final /* synthetic */ int f7437d;

    /* renamed from: e, reason: collision with root package name */
    public final /* synthetic */ C0585z f7438e;

    /* JADX WARN: 'super' call moved to the top of the method (can break code semantics) */
    public /* synthetic */ C0579t(C0585z c0585z, int i5) {
        super(0);
        this.f7437d = i5;
        this.f7438e = c0585z;
    }

    @Override // a3.InterfaceC0106a
    public final Object a() {
        C0585z c0585z = this.f7438e;
        switch (this.f7437d) {
            case 0:
                Collection collectionD = c0585z.d();
                ArrayList arrayList = new ArrayList(P2.o.l0(collectionD));
                Iterator it = collectionD.iterator();
                while (it.hasNext()) {
                    arrayList.add(new F(c0585z, (InterfaceC0765i) it.next()));
                }
                return arrayList;
            case 1:
                return c0585z.g(c0585z.r().q().p0(), 1);
            case 2:
                X3.n nVarW = c0585z.r().W();
                AbstractC0219i.d("descriptor.staticScope", nVarW);
                return c0585z.g(nVarW, 1);
            case 3:
                int i5 = C0585z.f7459g;
                N3.b bVarQ = c0585z.q();
                C0582w c0582w = (C0582w) c0585z.f.a();
                c0582w.getClass();
                InterfaceC0466p interfaceC0466p = AbstractC0559A.f7323b[0];
                Object objA = c0582w.f7324a.a();
                AbstractC0219i.d("<get-moduleData>(...)", objA);
                boolean z4 = bVarQ.f1832c;
                a4.i iVar = ((C0884f) objA).f9192a;
                InterfaceC0761e interfaceC0761eB = z4 ? iVar.b(bVarQ) : AbstractC0779w.d(iVar.f3038b, bVarQ);
                if (interfaceC0761eB != null) {
                    return interfaceC0761eB;
                }
                Class cls = c0585z.f7460e;
                C0881c c0881cA = AbstractC0807a.a(cls);
                H3.a aVar = c0881cA != null ? (H3.a) c0881cA.f9188b.f825d : null;
                switch (aVar == null ? -1 : AbstractC0583x.f7454a[aVar.ordinal()]) {
                    case -1:
                    case 6:
                        throw new O2.e("Unresolved class: " + cls, 2);
                    case 0:
                    default:
                        throw new O2.d();
                    case 1:
                    case 2:
                    case 3:
                        throw new UnsupportedOperationException("Packages and file facades are not yet supported in Kotlin reflection. Meanwhile please use Java reflection to inspect this class: " + cls);
                    case 4:
                        throw new UnsupportedOperationException("This class is an internal synthetic class generated by the Kotlin compiler, such as an anonymous class for a lambda, a SAM wrapper, a callable reference, etc. It's not a Kotlin class or interface, so the reflection library has no idea what declarations it has. Please use Java reflection to inspect this class: " + cls);
                    case 5:
                        throw new O2.e("Unknown class: " + cls + " (kind = " + aVar + ')', 2);
                }
            case 4:
                return c0585z.g(c0585z.r().q().p0(), 2);
            case 5:
                X3.n nVarW2 = c0585z.r().W();
                AbstractC0219i.d("descriptor.staticScope", nVarW2);
                return c0585z.g(nVarW2, 2);
            case 6:
                if (c0585z.f7460e.isAnonymousClass()) {
                    return null;
                }
                N3.b bVarQ2 = c0585z.q();
                if (bVarQ2.f1832c) {
                    return null;
                }
                return bVarQ2.b().b();
            default:
                return new C0582w(c0585z);
        }
    }
}
